GZ-1456 Change value of element clinicalStatus from "active" to "inac…
Nictiz/Nictiz-testscripts pull request #244
Opened 2024-01-24 15:46 UTC by Hdj81

…tive"

2024-01-25 10:55 UTC, LilianMinne requested changes
@Hdj81 kun je in het ticket nog een executielink toevoegen?

2024-01-25 12:37 UTC, Hdj81 commented
@LilianMinne ik heb het toegevoegd. Pieter heeft me nog een keer op weg geholpen met de executie

2024-01-25 14:24 UTC, LilianMinne approved these changes

2026-06-01 12:41 UTC, lisaDekker-nictiz commented
Closing this pull request because it is outdated and no longer aligned with the current codebase.

A new pull request can be opened if this change is still needed.

2026-06-01 12:41 UTC, closed without merging