MM-3607: Change operation type in PDF/A scenario 2.5
Nictiz/Nictiz-testscripts pull request #45
Opened 2022-10-13 06:02 UTC by LuudSlagter

2022-10-13 10:03 UTC, jduwel approved these changes

2022-10-13 20:23 UTC, pieter-edelman-nictiz requested changes
Ik vraag me af waarom je hier een component gebruikt, want je hebt het al met al maar één keer nodig in alle TestScripts. Zou het niet leesbaarder zijn om het gewoon in het TestScript te houden?

2022-10-14 06:14 UTC, LuudSlagter commented
Ik heb de component verwijderd, en de action direct in het testscript geplaatst.

2022-10-14 08:29 UTC, jduwel approved these changes

2022-10-18 13:40 UTC, pieter-edelman-nictiz approved these changes

2022-10-18 13:41 UTC, merged