MM-3686: OO toevoegen en gelijk trekken asserts
Nictiz/Nictiz-testscripts pull request #61
Opened 2022-11-10 11:45 UTC by yvettevdhaas

2022-11-10 16:27 UTC, FoppeCrezee approved these changes

2022-11-14 15:14 UTC, LuudSlagter approved these changes

2022-11-16 09:25 UTC, jduwel requested changes

2022-11-16 09:25 UTC, jduwel commented on src/common-components/assert.response.unsupportedResource.xml
>              <validateProfileId value="OperationOutcome-profile"/>
As the profile id is used here, the `nts:profile` element should also be placed within this `nts:component`. And following this, it should be removed from the individual NTS-files

2022-11-16 09:26 UTC, jduwel commented on src/common-components/assert.response.unsupportedResource.xml
>              <validateProfileId value="OperationOutcome-profile"/>
The output in dev shouldn't change because of this

2022-11-16 09:42 UTC, jduwel commented on src/common-components/assert.response.unsupportedResource.xml
>              <validateProfileId value="OperationOutcome-profile"/>
Appartently this common-component isn't included correctly? https://touchstone.aegis.net/touchstone/scriptexecution?exec=202211100843078086862099&qn=/FHIRSandbox/Nictiz/dev/FHIR3-0-2-MM202001-Cert/PDFA-3-0/XIS-Server-NoManifest/medmij-pdfa-xis-2-2-serve-2-documentmanifest-xml#WAITING_OPER is missing these checks completely

2022-11-16 12:25 UTC, merged