MM-3545 Changed general practitioner
Nictiz/Nictiz-testscripts pull request #9
Opened 2022-08-12 08:34 UTC by yvettevdhaas

2022-08-12 08:44 UTC, LuudSlagter commented
Please change 'main' to 'release-august'.

2022-08-15 06:39 UTC, LuudSlagter requested changes
Please also run the build-BgZ-3-0-Test.bat file, so that MM202001-Test within the dev folder is updated accordingly.

2022-08-15 06:39 UTC, LuudSlagter commented on Configuration/QualificationTokens.json
> -    "resourceId": "WIJZIGER",
Please revert these changes in this branch, as these are not related to this ticket.

2022-08-17 14:36 UTC, LuudSlagter approved these changes

2022-08-24 07:45 UTC, jduwel commented
@yvettevdhaas graag in je commit message het ticketnummer vermelden (graag het _originele_ nummer, niet die van de subtaak) en in de rest van de boodschap wat meer beschrijving over welke standaard het exact gaat. Alles met het doel om het straks als het op de 'grote hoop' ligt nog terug te kunnen vinden welke wijziging wanneer en waarom gedaan is

2022-08-24 07:53 UTC, merged